// Preview-only: resets this origin's demo companion, never Hermes storage.
async (page) => {
  const errors = [];
  page.on('pageerror', e => errors.push(e.message));
  const check = (ok, message) => { if (!ok) throw new Error(message); };
  const ready = () => page.waitForFunction(() => document.querySelector('.hp-stage') && !document.querySelector('.hp-loading'));
  await page.evaluate(() => { __demo.disable(); localStorage.removeItem('hermes-pokemon.demo.companion'); });
  await page.reload();
  await page.emulateMedia({reducedMotion:'no-preference'});
  await page.setViewportSize({width:1280,height:950});
  await page.waitForFunction(() => document.querySelectorAll('.hp-preview').length === 3);
  await page.waitForTimeout(500);
  const preview = await page.locator('.hp-preview').first().evaluate(c => c.toDataURL());
  await page.waitForFunction(previous => document.querySelector('.hp-preview').toDataURL() !== previous, preview, {timeout:5000});
  await page.screenshot({path:'docs/images/starters.png',fullPage:true});
  await page.getByRole('button',{name:/Charmander/}).click();
  await page.getByRole('textbox',{name:'A name for your new friend optional'}).fill('Dario');
  await page.getByRole('button',{name:'Meet your companion'}).click();
  await ready();
  await page.getByRole('button',{name:'Companion settings',exact:true}).click();
  await page.getByRole('radio',{name:'Day',exact:true}).click();
  await page.getByRole('button',{name:'Close settings'}).click();
  await page.getByRole('button',{name:'Pet',exact:true}).click();
  check(await page.evaluate(() => __hermesPokemonDebug.pet.bubble?.kind==='heart'), 'No pet reaction');
  await page.screenshot({path:'docs/images/habitat.png',fullPage:true});
  await page.reload();
  await ready();
  check(await page.evaluate(() => __demo.diagnostics().saved.nickname==='Dario' && __hermesPokemonDebug.pet.species==='charmander'), 'Selection did not persist');
  await page.getByRole('button',{name:'Companion settings',exact:true}).click();
  await page.getByRole('textbox', {name: 'Nickname'}).fill('Dario Jr');
  await page.getByRole('button',{name:'Save',exact:true}).click();
  await page.getByRole('button',{name:'Companion settings',exact:true}).click();
  await page.getByRole('button',{name:'Reset position',exact:true}).click();
  await page.getByRole('button',{name:'Companion settings',exact:true}).click();
  await page.getByRole('checkbox',{name:/Extra quiet mode/}).check();
  await page.getByRole('button',{name:'Close settings'}).click();
  await page.getByRole('button',{name:'Reload plugin',exact:true}).click();
  await ready();
  check(await page.evaluate(() => __demo.diagnostics().saved.nickname==='Dario Jr' && __hermesPokemonDebug.pet.reduced), 'Rename/quiet preference did not persist');
  await page.locator('#width').fill('240');
  await page.locator('#width').dispatchEvent('input');
  const narrow = await page.locator('.hp-root').evaluate(e => ({width:e.clientWidth,scroll:e.scrollWidth}));
  check(narrow.width===narrow.scroll && narrow.width<=240, 'Narrow pane overflows');
  await page.getByRole('button',{name:'Dark theme',exact:true}).click();
  await page.locator('.demo-pane').screenshot({path:'docs/images/narrow.png'});
  await page.getByRole('button',{name:'Dock beneath',exact:true}).click();
  check(await page.locator('body').evaluate(e=>e.classList.contains('bottom-dock')), 'Bottom docking failed');
  await page.getByRole('button',{name:'Dock beside',exact:true}).click();
  await page.getByRole('button',{name:'Light theme',exact:true}).click();
  await page.locator('#width').fill('370');
  await page.locator('#width').dispatchEvent('input');
  await page.getByRole('button',{name:'Companion settings',exact:true}).click();
  await page.getByRole('textbox', {name: 'Nickname'}).fill('Dario');
  await page.getByRole('button',{name:'Save',exact:true}).click();
  await page.getByRole('button',{name:'Companion settings',exact:true}).click();
  await page.getByRole('checkbox',{name:/Extra quiet mode/}).uncheck();
  await page.getByRole('button',{name:'Close settings'}).click();
  check(errors.length===0, errors.join('\n'));
  return {animatedStarters:true,pet:true,pageReloadPersistence:true,rename:true,reset:true,quietPreferencePersisted:true,narrow,bothThemes:true,bottomDock:true,errors};
}
