// Short status lines for every companion state, shown beneath the garden and read by screen readers.
export const CAPTIONS = {
  idle: "Taking it all in",
  walking: "Exploring the garden",
  coming: "Coming over!",
  resting: "Watching the leaves drift",
  basking: "Soaking up the sunshine",
  watching: "Watching the ripples",
  swimming: "Paddling around the pond",
  sniffing: "Smelling the flowers",
  sleeping: "A very important little nap",
  waking: "Waking up slowly…",
  playing: "Having a lovely time",
  petting: "That hit the spot!",
  attentive: "Keeping you company while Hermes works",
  celebrating: "A little cheer for a finished turn",
  waiting: "Hermes has a question for you. Tap me to go answer it",
  chasing: "On a very important mission",
  returning: "Bringing it back!",
  presenting: "Brought it back. Again?",
  anticipating: "Is that a berry for me?",
  eating: "Munch, munch…",
  greeting: "There you are!",
  noticing: "You have my attention",
  tending: "Giving the flowers a little care",
  warming: "Warming those tiny paws",
  rippling: "One little ripple, then another",
  inviting: "Brought a ball. Want to play?",
  investigating: "Taking a closer look with you",
  evolving: "Ready for a new chapter",
  company: "Sitting with you while Hermes works on a long one",
  proud: "That was a long one. Well done, both of you!",
  steady: "Hmm, that one didn't land. Still here",
  stopped: "Stopped. That's okay",
  offering: "Rough patch? Maybe a little break",
  treasure: "Found something! Keeping it safe",
  expecting: "Right on time. Waiting in our usual spot",
  blossoms: "Watching the blossoms drift down",
  "tail-warming": "Keeping warm by its own tail flame",
  "leaf-watching": "Watching leaves float on the pond",
  "snow-watching": "Watching snowflakes melt on the water",
  scouting: "Looking out over the fence while Hermes searches",
  curious: "Curious about what Hermes is running",
  digging: "Digging a little while Hermes writes",
  puddling: "Splashing in the rain. Best day ever",
  sheltering: "Keeping its flame dry under the tree",
  soaking: "Turning its bulb up to the rain",
  sleepy: "Yawning. It's getting late",
  dozing: "Dozing off beside you. It's late",
  visitor: "Watching a wild visitor",
  admiring: "Checking on a keepsake",
  milestone: "Another milestone together",
  elsewhere: "Something finished in another chat",
  bench: "Resting by the bench you earned together",
  lanternlit: "Sitting in the lantern light",
};
